### ISSUE TITLE
Bug ? ID value is converted to date

### ISSUE THREAD

**Issue by roysbike** [marcusolsson/grafana-jsonapi-datasource#10]
<img width="1337" alt="id" src="https://user-images.githubusercontent.com/2388223/98223228-e2f69900-1f62-11eb-9b89-34e78a8a0db9.png">

Please , help. ID value is converted to date
[crm.deal.list.json.zip](https://github.com/marcusolsson/grafana-jsonapi-datasource/files/5493302/crm.deal.list.json.zip)

**Comment by marcusolsson** [comment]
Thanks for reporting this! I'll have time to look at this during this weekend!

**Comment by marcusolsson** [comment]
Unfortunately, I'm unable to replicate this with the dataset you sent me. 

The field should only be set to a time field if _all_ values share any of these conditions:

- All values are valid ISO8601 strings
- All values are numbers with a length of 10 (seconds)
- All values are numbers with a length of 13 (milliseconds)

I don't understand why a string like `"1502"` would get detected as a timestamp tbh. Could you try creating a panel from scratch and try this? Just in case there are other settings interfering?

<img width="1289" alt="Screen Shot 2020-11-09 at 15 26 29" src="https://user-images.githubusercontent.com/8396880/98553480-f32eb100-229f-11eb-92c6-69ff86026bdb.png">

**Comment by roysbike** [comment]
When I create a panel, the IDs are first determined correctly. When I save it and make a link, the ID is set with the date.

**Comment by roysbike** [comment]
![image](https://user-images.githubusercontent.com/2388223/98649713-f2058e80-2348-11eb-855d-65e7be60351d.png)

Check please this file 


[deal.json.zip](https://github.com/marcusolsson/grafana-jsonapi-datasource/files/5515930/deal.json.zip)

**Comment by marcusolsson** [comment]
Ok, I know why this happens. Since `3942` is technically a valid ISO 8601 string, it gets parsed as a time field. I'll try to publish a fix within the next few days.

**Comment by marcusolsson** [comment]
v0.6.0 has now been published with this fix. Thanks!
