### ISSUE TITLE
Data can not be displayed as Graph

### ISSUE THREAD

**Issue by gregorschulte-uni** [marcusolsson/grafana-jsonapi-datasource#12]
Good Day,

I am having trouble displaying data from thingspeak via the JSON API datasource plugin.

I am using the following URL to get a the data as JSON from thingspeak:
https://api.thingspeak.com/channels/1103934/fields/1.json?days=7

As query I use the JSON paths
“.feeds[\*].field1" and ".feeds[\*].created_at”
successfully generating a table.

![grafana](https://user-images.githubusercontent.com/29063878/98520404-45f17400-2272-11eb-9c1a-716371a192ca.png)

I do not know if i am doing somthing wrong here.

**Comment by marcusolsson** [comment]
The graph panel requires a time field and a number field. It looks like like field1 is a string property in the response you linked to. We'd have to add some basic text-to-number transformation to support this. Is there a reason why `field1` is of type string?

**Comment by gregorschulte-uni** [comment]
Thank you Marcus. After looking at detectFileType and my data it might be the missing data represented as null in the json from thingspeak resulting in a definition as string.

**Comment by marcusolsson** [comment]
Just wanted to let you know there's a bug that incorrectly sets a time field when all values are strings of 4 integers (because it's a valid ISO8601). For more information, check out #10.

I've published a new version (0.6.0) with a fix in case you run into this. If not, please let me know if we can close this issue.

**Comment by gregorschulte-uni** [comment]
I thing I never ran into that specific problem. Data recognition always worked fine. 

Right now I am busy setting up a local grafana instance to see what I can do do fix the "string" issue. When assuming everything coming in is a number this works already:
![image](https://user-images.githubusercontent.com/29063878/99370873-81b5ba80-28be-11eb-9e23-a3e62fe1cfd2.png)


![image](https://user-images.githubusercontent.com/29063878/99370666-43b89680-28be-11eb-9c8f-592d3b75f8cf.png)

I guess I will have to add some kind of conversion / format checking to make it more robust.

**Comment by marcusolsson** [comment]
Looks awesome! :) I'm going ahead and closing this issue for now, but feel free to open another one if you run into trouble!
