### ISSUE TITLE
Dynamic parameter by the variable of grafana

### ISSUE THREAD

**Issue by happy0108** [marcusolsson/grafana-jsonapi-datasource#13]
Could add a function to link the variable of grafana. so it can change the parameter.

**Comment by marcusolsson** [comment]
Could you give me an example of what you'd like it to do? If you're referring to template variables, you can already use them in the JSON path, as well as in the Alias.

Here's an example:

<img width="995" alt="Screen Shot 2020-11-18 at 08 53 55" src="https://user-images.githubusercontent.com/8396880/99501110-999f4400-297b-11eb-9146-e4160b1f81b0.png">

**Comment by mbarradas** [comment]
Great I was able to use it. I needed to remove the cache time since the variable was not updated until I refreshed the dashboard.
It now works as expected on my side.

**Comment by happy0108** [comment]
Like this, thanks.
![grafanalink](https://user-images.githubusercontent.com/41312037/99611695-1818e600-2a4f-11eb-818b-514164239f9b.png)

**Comment by mbarradas** [comment]
Just put the employeeid=$ID

**Comment by happy0108** [comment]
It cannot work by this way. There's no result showed by "employeeid=$ID".
![Capture](https://user-images.githubusercontent.com/41312037/99616711-aba2e480-2a58-11eb-83dd-aeabe1f1599f.PNG)

**Comment by marcusolsson** [comment]
Variable support for custom query parameters was recently fixed in 0.6.1 so make sure you have the latest version. Also, the syntax for template variables is `${variable}`. Note that you need to use the name of the variable, not the label (I can't tell from the screenshot whether `ID` is the name or label).

**Comment by happy0108** [comment]
when i update the plugin to version 0.6.1, it's worked now, thanks a lot.
