### ISSUE TITLE
Grafana variable in "Custom queries parameter"

### ISSUE THREAD

**Issue by Tugduall** [marcusolsson/grafana-jsonapi-datasource#14]
Using the global variables in the "Custom queries parametre" field to change the API parameters during the call, would be a very useful feature. 

Is it planned?

Thanks

**Comment by marcusolsson** [comment]
No, but it's easy to add. I'll fix this during the week. Thanks for letting me know! 🙏

**Comment by marcusolsson** [comment]
Fixed in [v0.6.1](https://grafana.com/grafana/plugins/marcusolsson-json-datasource?version=0.6.1). Let me know if you're having any issues!

**Comment by enavarro222** [comment]
Thanks that's perfect for me !
