### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by mbarradas** [marcusolsson/grafana-jsonapi-datasource#2]
I would be nice If we could configure it with Basic Authentication since not all the JSON Apis are token based.

**Comment by marcusolsson** [comment]
I'll get right on this!

**Comment by marcusolsson** [comment]
Added in [v0.4.0](https://grafana.com/grafana/plugins/marcusolsson-json-datasource?version=0.4.0). Thanks for the feature request!
