### ISSUE TITLE
How to use variable in JSON API?

### ISSUE THREAD

**Issue by minhkhoa0502** [marcusolsson/grafana-jsonapi-datasource#7]
Hi,

I declared $namespace variable as query in Grafana. But I can't use it to filter.

Could you please help me how to use variable in JSON PATH?

Thanks.

**Comment by marcusolsson** [comment]
Hi! This was added in https://github.com/marcusolsson/grafana-jsonapi-datasource/pull/6, but I haven't had the chance to release it yet. I hope to do it this week 👍

**Comment by minhkhoa0502** [comment]
Hope to see it soon :D

**Comment by alexthickett** [comment]
any update on a timeframe for this?

Seems very useful and looks like it could solve a couple issues for me.

**Comment by marcusolsson** [comment]
This was released in v0.5.0 and has been published to Grafana.com. Let me know if you have any problems.
