### ISSUE TITLE
Custom query parameters and URL via query

### ISSUE THREAD

**Issue by tomglazer89** [marcusolsson/grafana-jsonapi-datasource#8]
Hey!
Thanks for the plugin, its great 👍 

is it possible to add an option to pass **URL** or **Custom query parameter**s from the dashboard query?

because now i have to create a new data source for each request i make (even if in the same api scope)

Thanks!

**Comment by mbarradas** [comment]
I have the same issue I would like to send a Variable to the JSON call but it seems we are not capable of interacting with the call withing the dashboard.

**Comment by marcusolsson** [comment]
Thanks both of you for the feature request! I think makes perfect sense to add something like this to the query editor. Would be pretty easy to implement as well.

**Comment by enavarro222** [comment]
This feature may be very useful !

**Comment by marcusolsson** [comment]
I've published v0.6.0 with this feature. Let me know if it works for you!

**Comment by Tugduall** [comment]
Hey !

Thank you for the plugin. Can we use dashboard global variable in "Custom query parameters" ?

Thanks

**Comment by tomglazer89** [comment]
Thanks Marcus! will check it up!
do you  also plan to add passing the URL from the query to the data source?

**Comment by mbarradas** [comment]
Hi I just updated the panel and it's close to what I expected but it seems
it's not capable of grabbing the Variables from the dashboard.
If I override the query and put the variable value as plain text it works
but If I try the same with a variable the Dashboard won't update.
Thanks for the update.

**Comment by enavarro222** [comment]
No issue with last versions to use variable in custom query !
<img width="843" alt="image" src="https://user-images.githubusercontent.com/1804076/99717064-2ac00900-2aa9-11eb-9558-c31ff0f51ddb.png">

**Comment by marcusolsson** [comment]
> Thanks Marcus! will check it up!
> do you also plan to add passing the URL from the query to the data source?

I'm afraid I don't understand what you mean by this. Could you give an example?

**Comment by tomglazer89** [comment]
Hey Marcus,
sorry ill try to explain better.

I'm not sure if its something possible to implement on grafana. :)  

this is my scenario, I have 4 servers with JSON api, exposed on the following addresses:
http://server1/api
http://server2/api
http://server3/api
http://server4/api

then i have a Grafana variable with these4 servers as drop down list.

when you select one of these servers, each one is bounded to its own data source. i had to put their data source as a variable, and create 4 different data sources.

its not so much a big issue, but if you have 10 servers, then you need to add 10 data sources...

my question is, is it possible to create 1 generic JSON data source, and then (as same as you passed the custom URL parameters from the query) pass the URL as a variable to the generic data source?
so this way I have only 1 data source, with  a dynamic URL.

for now, my workaround was to create a php file as router, and redirect to the selected server.
something like:
http://mainserver?server=server1

then inside the php i redirect the request to:
http://server1/api
this way I only have 1 data source.

Thanks!!

**Comment by marcusolsson** [comment]
I don't think I've seen this pattern before, but there's nothing stopping us from adding a variable to the URL in the data source configuration and interpolating it for each query. Could you open a new issue for this maybe?
