### ISSUE TITLE
How to use filter  ?

### ISSUE THREAD

**Issue by roysbike** [marcusolsson/grafana-jsonapi-datasource#9]
I need filter if STATUS = 5

`$.result[*].[STATUS=5]
`

**Comment by marcusolsson** [comment]
Haven't tested it, but I think you should be able to use the `?` operator to filter results.

For an array like this:

```
{
  "result": [
    {
      "name": "Foo",
      "status": 5
    },
    {
     "name": "Bar",
      "status": 3
    },
  ]
}
```

You could write this:

```
$.result[?(@.status == 5)].name
```

to get this:

```
["Foo"]
```

**Comment by roysbike** [comment]
thk! is working!
